width = float(input('ป้อนความกว้าง : '))
long = float(input('ป้อนความยาว : '))
hight = float(input('ป้อนความสูง : '))
area = round(((width * long * 2 )+(width * hight * 2)+(long * hight * 2) ) / 5 )
print ('===========================')
print ('กล่องสี่เหลี่ยมที่มีความกว้าง ', width , 'ยาว' , long , 'สูง' , hight , 'ต้องใช้สีทั้งหมด' , area ,'แกลอน')
print ('กล่องสี่เหลี่ยมที่มีความกว้าง '+ str(width) + 'ยาว' + str(long) + 'สูง' + str(hight) + 'ต้องใช้สีทั้งหมด' + str(area) +'แกลอน')
print (f'กล่องสี่เหลี่ยมที่มีความกว้าง {width} ยาว {long} สูง {hight} ต้องใช้สีทั้งหมด {area} แกลอน')
print ('กล่องสี่เหลี่ยมที่มีความ {} ยาว {} สูง {} ต้องใช้สีทั้งหมด {} แกลอน' .format(width,long,hight,area))