Money = int(input('จำนวนเงิน'))
people = float(input('จำนวนคน'))
result= float(Money) / (people)
a= format(float(result),'.2f')
print('----------------------')
print(f'มีพนักงาน {people} มีเงิน {Money} หารคนละ {result} บาท')
print('มีพนักงาน', people ,'มีเงิน', str(a), 'หารคนละ', str(result),'บาท')
print('มีพนักงาน'+ str(people)+'มีเงิน'+ str(a)+'หารคนละ'+str(result)+'บาท')
print('มีพนักงาน {} มีเงิน {} หารคนละ {} บาท'.format(people,Money,result) )
